# Generated by Django 2.0 on 2018-01-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('day', models.DateField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('vol', models.FloatField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ReportData',
            fields=[
                ('code', models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('eps', models.FloatField(null=True)),
                ('eps_yoy', models.FloatField(null=True)),
                ('bvps', models.FloatField(null=True)),
                ('roe', models.FloatField(null=True)),
                ('epcf', models.FloatField(null=True)),
                ('net_profits', models.FloatField(null=True)),
                ('profits_yoy', models.FloatField(null=True)),
                ('distrib', models.CharField(max_length=16, null=True)),
                ('report_date', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='StockBasics',
            fields=[
                ('code', models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('industry', models.CharField(max_length=8)),
                ('area', models.CharField(max_length=8)),
                ('pe', models.FloatField()),
                ('outstanding', models.FloatField()),
                ('totals', models.FloatField()),
                ('totalAssets', models.FloatField()),
                ('liquidAssets', models.FloatField()),
                ('fixedAssets', models.FloatField()),
                ('reserved', models.FloatField()),
                ('reservedPerShare', models.FloatField()),
                ('eps', models.FloatField()),
                ('bvps', models.FloatField()),
                ('pb', models.FloatField()),
                ('timeToMarket', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('code', 'day')},
        ),
    ]
