# Generated by Django 2.1.4 on 2019-01-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('day', models.DateField()),
                ('policy', models.CharField(max_length=4)),
                ('comments', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('code', models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False)),
                ('createDay', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('code', models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False)),
                ('codePrice', models.FloatField()),
                ('priceToSell', models.FloatField()),
                ('priceToStop', models.FloatField()),
                ('createDay', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('code', 'day')},
        ),
    ]
