# Generated by Django 2.1.4 on 2019-01-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('code', models.CharField(db_index=True, max_length=6, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('industry', models.CharField(max_length=8)),
                ('policy', models.CharField(max_length=4)),
                ('priceToBuy', models.FloatField()),
                ('priceToSell', models.FloatField()),
                ('reasonToInterest', models.TextField()),
                ('reasonToBuy', models.TextField()),
                ('reasonToHold', models.TextField()),
                ('reasonToSell', models.TextField()),
                ('createDay', models.DateField()),
                ('updateDay', models.DateField()),
            ],
        ),
    ]
